### ISSUE TITLE
worldPing Event Dashboard errors

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#14] opened 2016-03-28 03:00 UTC
When loading the event dashboard, get these errors on the panels:
<img width="843" alt="screenshot 2016-03-27 22 59 33" src="https://cloud.githubusercontent.com/assets/2886187/14070046/aa01005e-f46f-11e5-907c-7976649959f4.png">

<img width="205" alt="screenshot 2016-03-27 22 01 42" src="https://cloud.githubusercontent.com/assets/2886187/14070051/b4242192-f46f-11e5-9a6c-f810a0d5561c.png">
<img width="423" alt="screenshot 2016-03-27 22 01 36" src="https://cloud.githubusercontent.com/assets/2886187/14070050/b4225b96-f46f-11e5-9c2e-eec68b02420b.png">

**Comment by woodsaj** [comment] 2016-03-28 03:10
I think this has laready been fixed. This problem happens when the es dataslurce is configured as es version 2.  But it is now set to use version 1.

You will need to delete and recreate the datasources for the change to take affect.

**Comment by woodsaj** [comment] 2016-03-28 03:39
ok, found the issue.  The problem is to do with probes that have "-" in them.

these are being escaped and the events index should be configured to not analyse these terms (ie it should not try and split it into words).  will need to look into index mapping on ES.

**Comment by woodsaj** [comment] 2016-03-28 04:03
ok, the issue is that the index mapping didn't have "index: not_analysed" set for the tag values.

This has been fixed with https://github.com/raintank/raintank-metric/commit/1bb80715aad57bc2a2daee89bec11b0aea0449e7 and i will now deploy this to production.

The change wont take affect until 00:00 utc when a new index is created.  every event after that will then be index properly.

**Closed** 2016-04-04 13:34 UTC
